import { Permission } from "@/types";

// All system permissions
export const ALL_PERMISSIONS: Permission[] = [
  // Bus Management
  {
    id: "perm_001",
    name: "View Buses",
    slug: "BUS_VIEW",
    category: "Bus Management",
    description: "View bus list and details",
    isSystemPermission: true,
  },
  {
    id: "perm_002",
    name: "Create Bus",
    slug: "BUS_CREATE",
    category: "Bus Management",
    description: "Add new buses",
    isSystemPermission: true,
  },
  {
    id: "perm_003",
    name: "Edit Bus",
    slug: "BUS_EDIT",
    category: "Bus Management",
    description: "Edit bus information",
    isSystemPermission: true,
  },
  {
    id: "perm_004",
    name: "Delete Bus",
    slug: "BUS_DELETE",
    category: "Bus Management",
    description: "Delete buses",
    isSystemPermission: true,
  },
  {
    id: "perm_005",
    name: "View Bus Layout",
    slug: "BUS_LAYOUT_VIEW",
    category: "Bus Management",
    description: "View bus seat layout",
    isSystemPermission: true,
  },
  {
    id: "perm_006",
    name: "Edit Bus Layout",
    slug: "BUS_LAYOUT_EDIT",
    category: "Bus Management",
    description: "Edit bus seat layout",
    isSystemPermission: true,
  },
  {
    id: "perm_073",
    name: "Create Bus Layout",
    slug: "BUS_LAYOUT_CREATE",
    category: "Bus Management",
    description: "Create new bus layouts",
    isSystemPermission: true,
  },
  {
    id: "perm_074",
    name: "Delete Bus Layout",
    slug: "BUS_LAYOUT_DELETE",
    category: "Bus Management",
    description: "Delete bus layouts",
    isSystemPermission: true,
  },
  {
    id: "perm_075",
    name: "Assign Bus Layout",
    slug: "BUS_LAYOUT_ASSIGN",
    category: "Bus Management",
    description: "Assign layouts to buses",
    isSystemPermission: true,
  },
  {
    id: "perm_007",
    name: "View Bus Analytics",
    slug: "BUS_ANALYTICS_VIEW",
    category: "Bus Management",
    description: "View bus-specific analytics",
    isSystemPermission: true,
  },

  // Driver Management
  {
    id: "perm_008",
    name: "View Drivers",
    slug: "DRIVER_VIEW",
    category: "Driver Management",
    description: "View driver list and details",
    isSystemPermission: true,
  },
  {
    id: "perm_009",
    name: "Create Driver",
    slug: "DRIVER_CREATE",
    category: "Driver Management",
    description: "Add new drivers",
    isSystemPermission: true,
  },
  {
    id: "perm_010",
    name: "Edit Driver",
    slug: "DRIVER_EDIT",
    category: "Driver Management",
    description: "Edit driver information",
    isSystemPermission: true,
  },
  {
    id: "perm_011",
    name: "Delete Driver",
    slug: "DRIVER_DELETE",
    category: "Driver Management",
    description: "Remove drivers",
    isSystemPermission: true,
  },
  {
    id: "perm_012",
    name: "Assign Driver",
    slug: "DRIVER_ASSIGN",
    category: "Driver Management",
    description: "Assign drivers to buses/trips",
    isSystemPermission: true,
  },
  {
    id: "perm_013",
    name: "View Driver Schedule",
    slug: "DRIVER_SCHEDULE_VIEW",
    category: "Driver Management",
    description: "View driver schedules",
    isSystemPermission: true,
  },

  // Route & Stop Management
  {
    id: "perm_014",
    name: "View Routes",
    slug: "ROUTE_VIEW",
    category: "Route Management",
    description: "View routes",
    isSystemPermission: true,
  },
  {
    id: "perm_015",
    name: "Create Route",
    slug: "ROUTE_CREATE",
    category: "Route Management",
    description: "Create new routes",
    isSystemPermission: true,
  },
  {
    id: "perm_016",
    name: "Edit Route",
    slug: "ROUTE_EDIT",
    category: "Route Management",
    description: "Edit route details",
    isSystemPermission: true,
  },
  {
    id: "perm_017",
    name: "Delete Route",
    slug: "ROUTE_DELETE",
    category: "Route Management",
    description: "Delete routes",
    isSystemPermission: true,
  },
  {
    id: "perm_018",
    name: "View Stops",
    slug: "STOP_VIEW",
    category: "Route Management",
    description: "View stops",
    isSystemPermission: true,
  },
  {
    id: "perm_019",
    name: "Create Stop",
    slug: "STOP_CREATE",
    category: "Route Management",
    description: "Add stops to routes",
    isSystemPermission: true,
  },
  {
    id: "perm_020",
    name: "Edit Stop",
    slug: "STOP_EDIT",
    category: "Route Management",
    description: "Edit stop information",
    isSystemPermission: true,
  },
  {
    id: "perm_021",
    name: "Delete Stop",
    slug: "STOP_DELETE",
    category: "Route Management",
    description: "Remove stops from routes",
    isSystemPermission: true,
  },

  // Trip Management
  {
    id: "perm_022",
    name: "View Trips",
    slug: "TRIP_VIEW",
    category: "Trip Management",
    description: "View trip assignments",
    isSystemPermission: true,
  },
  {
    id: "perm_023",
    name: "Create Trip",
    slug: "TRIP_CREATE",
    category: "Trip Management",
    description: "Create trip assignments",
    isSystemPermission: true,
  },
  {
    id: "perm_024",
    name: "Edit Trip",
    slug: "TRIP_EDIT",
    category: "Trip Management",
    description: "Edit trip assignments",
    isSystemPermission: true,
  },
  {
    id: "perm_025",
    name: "Delete Trip",
    slug: "TRIP_DELETE",
    category: "Trip Management",
    description: "Delete/cancel trip assignments",
    isSystemPermission: true,
  },
  {
    id: "perm_026",
    name: "View Trip Details",
    slug: "TRIP_DETAILS_VIEW",
    category: "Trip Management",
    description: "View trip details",
    isSystemPermission: true,
  },
  {
    id: "perm_027",
    name: "Edit Trip Details",
    slug: "TRIP_DETAILS_EDIT",
    category: "Trip Management",
    description: "Edit trip details",
    isSystemPermission: true,
  },
  {
    id: "perm_028",
    name: "Cancel Trip",
    slug: "TRIP_CANCEL",
    category: "Trip Management",
    description: "Cancel trips",
    isSystemPermission: true,
  },
  {
    id: "perm_029",
    name: "View Trip Passengers",
    slug: "TRIP_PASSENGERS_VIEW",
    category: "Trip Management",
    description: "View passenger list for trips",
    isSystemPermission: true,
  },
  {
    id: "perm_030",
    name: "Update Trip Status",
    slug: "TRIP_STATUS_UPDATE",
    category: "Trip Management",
    description: "Update trip status (delay, on-time, etc.)",
    isSystemPermission: true,
  },

  // User Management
  {
    id: "perm_031",
    name: "View Users",
    slug: "USER_VIEW",
    category: "User Management",
    description: "View user list and details",
    isSystemPermission: true,
  },
  {
    id: "perm_032",
    name: "Edit User",
    slug: "USER_EDIT",
    category: "User Management",
    description: "Edit user information",
    isSystemPermission: true,
  },
  {
    id: "perm_033",
    name: "Block User",
    slug: "USER_BLOCK",
    category: "User Management",
    description: "Block/unblock users",
    isSystemPermission: true,
  },
  {
    id: "perm_034",
    name: "Delete User",
    slug: "USER_DELETE",
    category: "User Management",
    description: "Delete user accounts",
    isSystemPermission: true,
  },
  {
    id: "perm_035",
    name: "View User Bookings",
    slug: "USER_BOOKINGS_VIEW",
    category: "User Management",
    description: "View user booking history",
    isSystemPermission: true,
  },
  {
    id: "perm_036",
    name: "View User Payments",
    slug: "USER_PAYMENT_VIEW",
    category: "User Management",
    description: "View user payment history",
    isSystemPermission: true,
  },

  // Booking Management
  {
    id: "perm_037",
    name: "View Bookings",
    slug: "BOOKING_VIEW",
    category: "Booking Management",
    description: "View all bookings",
    isSystemPermission: true,
  },
  {
    id: "perm_038",
    name: "Create Booking",
    slug: "BOOKING_CREATE",
    category: "Booking Management",
    description: "Create bookings (for users)",
    isSystemPermission: true,
  },
  {
    id: "perm_039",
    name: "Edit Booking",
    slug: "BOOKING_EDIT",
    category: "Booking Management",
    description: "Edit booking details",
    isSystemPermission: true,
  },
  {
    id: "perm_040",
    name: "Cancel Booking",
    slug: "BOOKING_CANCEL",
    category: "Booking Management",
    description: "Cancel bookings",
    isSystemPermission: true,
  },
  {
    id: "perm_041",
    name: "View Booking Payment",
    slug: "BOOKING_PAYMENT_VIEW",
    category: "Booking Management",
    description: "View payment information",
    isSystemPermission: true,
  },
  {
    id: "perm_042",
    name: "Verify Booking Payment",
    slug: "BOOKING_PAYMENT_VERIFY",
    category: "Booking Management",
    description: "Verify/confirm payments",
    isSystemPermission: true,
  },

  // Analytics & Reports
  {
    id: "perm_043",
    name: "View Analytics",
    slug: "ANALYTICS_VIEW",
    category: "Analytics",
    description: "View analytics dashboard",
    isSystemPermission: true,
  },
  {
    id: "perm_044",
    name: "View All Analytics",
    slug: "ANALYTICS_VIEW_ALL",
    category: "Analytics",
    description: "View all analytics including financial",
    isSystemPermission: true,
  },
  {
    id: "perm_045",
    name: "View Revenue",
    slug: "REVENUE_VIEW",
    category: "Analytics",
    description: "View revenue reports and data",
    isSystemPermission: true,
  },
  {
    id: "perm_046",
    name: "Generate Reports",
    slug: "REPORTS_GENERATE",
    category: "Analytics",
    description: "Generate custom reports",
    isSystemPermission: true,
  },
  {
    id: "perm_047",
    name: "Export Reports",
    slug: "REPORTS_EXPORT",
    category: "Analytics",
    description: "Export reports (PDF/Excel/CSV)",
    isSystemPermission: true,
  },

  // Live Tracking
  {
    id: "perm_048",
    name: "View Tracking",
    slug: "TRACKING_VIEW",
    category: "Live Tracking",
    description: "View live bus tracking",
    isSystemPermission: true,
  },
  {
    id: "perm_049",
    name: "Monitor Tracking",
    slug: "TRACKING_MONITOR",
    category: "Live Tracking",
    description: "Monitor all buses in real-time",
    isSystemPermission: true,
  },
  {
    id: "perm_050",
    name: "View Tracking History",
    slug: "TRACKING_HISTORY",
    category: "Live Tracking",
    description: "View historical tracking data",
    isSystemPermission: true,
  },

  // Support & Notifications
  {
    id: "perm_051",
    name: "View Support Tickets",
    slug: "SUPPORT_TICKET_VIEW",
    category: "Support",
    description: "View support tickets",
    isSystemPermission: true,
  },
  {
    id: "perm_052",
    name: "Create Support Ticket",
    slug: "SUPPORT_TICKET_CREATE",
    category: "Support",
    description: "Create support tickets",
    isSystemPermission: true,
  },
  {
    id: "perm_053",
    name: "Edit Support Ticket",
    slug: "SUPPORT_TICKET_EDIT",
    category: "Support",
    description: "Edit ticket details",
    isSystemPermission: true,
  },
  {
    id: "perm_054",
    name: "Resolve Support Ticket",
    slug: "SUPPORT_TICKET_RESOLVE",
    category: "Support",
    description: "Resolve/close tickets",
    isSystemPermission: true,
  },
  {
    id: "perm_055",
    name: "View Notifications",
    slug: "NOTIFICATION_VIEW",
    category: "Support",
    description: "View notifications",
    isSystemPermission: true,
  },
  {
    id: "perm_056",
    name: "Send Notifications",
    slug: "NOTIFICATION_SEND",
    category: "Support",
    description: "Send notifications to users/drivers",
    isSystemPermission: true,
  },

  // Admin Management
  {
    id: "perm_057",
    name: "View Admins",
    slug: "ADMIN_VIEW",
    category: "Admin Management",
    description: "View admin list and details",
    isSystemPermission: true,
  },
  {
    id: "perm_058",
    name: "Create Admin",
    slug: "ADMIN_CREATE",
    category: "Admin Management",
    description: "Create new admin accounts",
    isSystemPermission: true,
  },
  {
    id: "perm_059",
    name: "Edit Admin",
    slug: "ADMIN_EDIT",
    category: "Admin Management",
    description: "Edit admin information",
    isSystemPermission: true,
  },
  {
    id: "perm_060",
    name: "Delete Admin",
    slug: "ADMIN_DELETE",
    category: "Admin Management",
    description: "Delete admin accounts",
    isSystemPermission: true,
  },
  {
    id: "perm_061",
    name: "Suspend Admin",
    slug: "ADMIN_SUSPEND",
    category: "Admin Management",
    description: "Suspend/activate admin accounts",
    isSystemPermission: true,
  },
  {
    id: "perm_062",
    name: "Reset Admin Password",
    slug: "ADMIN_PASSWORD_RESET",
    category: "Admin Management",
    description: "Reset admin passwords",
    isSystemPermission: true,
  },

  // Role Management
  {
    id: "perm_063",
    name: "View Roles",
    slug: "ROLE_VIEW",
    category: "Role Management",
    description: "View roles list",
    isSystemPermission: true,
  },
  {
    id: "perm_064",
    name: "Create Role",
    slug: "ROLE_CREATE",
    category: "Role Management",
    description: "Create new roles",
    isSystemPermission: true,
  },
  {
    id: "perm_065",
    name: "Edit Role",
    slug: "ROLE_EDIT",
    category: "Role Management",
    description: "Edit role details and permissions",
    isSystemPermission: true,
  },
  {
    id: "perm_066",
    name: "Delete Role",
    slug: "ROLE_DELETE",
    category: "Role Management",
    description: "Delete roles (except system roles)",
    isSystemPermission: true,
  },
  {
    id: "perm_067",
    name: "View Permissions",
    slug: "PERMISSION_VIEW",
    category: "Role Management",
    description: "View all permissions",
    isSystemPermission: true,
  },
  {
    id: "perm_068",
    name: "Manage Permissions",
    slug: "PERMISSION_MANAGE",
    category: "Role Management",
    description: "Manage role-permission mappings",
    isSystemPermission: true,
  },

  // System Settings
  {
    id: "perm_069",
    name: "View System Settings",
    slug: "SYSTEM_SETTINGS_VIEW",
    category: "System",
    description: "View system settings",
    isSystemPermission: true,
  },
  {
    id: "perm_070",
    name: "Edit System Settings",
    slug: "SYSTEM_SETTINGS_EDIT",
    category: "System",
    description: "Edit system configuration",
    isSystemPermission: true,
  },
  {
    id: "perm_071",
    name: "View System Logs",
    slug: "SYSTEM_LOGS_VIEW",
    category: "System",
    description: "View system activity logs",
    isSystemPermission: true,
  },
  {
    id: "perm_072",
    name: "System Backup",
    slug: "SYSTEM_BACKUP",
    category: "System",
    description: "Create system backups",
    isSystemPermission: true,
  },
];

// Permission categories for grouping
export const PERMISSION_CATEGORIES = [
  "Bus Management",
  "Driver Management",
  "Route Management",
  "Trip Management",
  "User Management",
  "Booking Management",
  "Analytics",
  "Live Tracking",
  "Support",
  "Admin Management",
  "Role Management",
  "System",
];

export const permissionService = {
  getAll: (): Permission[] => {
    return ALL_PERMISSIONS;
  },

  getById: (id: string): Permission | undefined => {
    return ALL_PERMISSIONS.find((p) => p.id === id);
  },

  getBySlug: (slug: string): Permission | undefined => {
    return ALL_PERMISSIONS.find((p) => p.slug === slug);
  },

  getByCategory: (category: string): Permission[] => {
    return ALL_PERMISSIONS.filter((p) => p.category === category);
  },

  getCategories: (): string[] => {
    return PERMISSION_CATEGORIES;
  },

  getPermissionSlugs: (permissionIds: string[]): string[] => {
    return ALL_PERMISSIONS.filter((p) => permissionIds.includes(p.id)).map((p) => p.slug);
  },
};
