/**
 * Centralized permission slugs used across the application.
 * Follows the naming convention: MODULE_ACTION
 */
export const PERMISSIONS = {
  // Bus Management
  BUS_VIEW: "BUS_VIEW",
  BUS_CREATE: "BUS_CREATE",
  BUS_EDIT: "BUS_EDIT",
  BUS_DELETE: "BUS_DELETE",
  BUS_LAYOUT_VIEW: "BUS_LAYOUT_VIEW",
  BUS_LAYOUT_EDIT: "BUS_LAYOUT_EDIT",
  BUS_LAYOUT_CREATE: "BUS_LAYOUT_CREATE",
  BUS_LAYOUT_DELETE: "BUS_LAYOUT_DELETE",
  BUS_LAYOUT_ASSIGN: "BUS_LAYOUT_ASSIGN",
  BUS_ANALYTICS_VIEW: "BUS_ANALYTICS_VIEW",

  // Driver Management
  DRIVER_VIEW: "DRIVER_VIEW",
  DRIVER_CREATE: "DRIVER_CREATE",
  DRIVER_EDIT: "DRIVER_EDIT",
  DRIVER_DELETE: "DRIVER_DELETE",
  DRIVER_ASSIGN: "DRIVER_ASSIGN",
  DRIVER_SCHEDULE_VIEW: "DRIVER_SCHEDULE_VIEW",

  // Route & Stop Management
  ROUTE_VIEW: "ROUTE_VIEW",
  ROUTE_CREATE: "ROUTE_CREATE",
  ROUTE_EDIT: "ROUTE_EDIT",
  ROUTE_DELETE: "ROUTE_DELETE",
  STOP_VIEW: "STOP_VIEW",
  STOP_CREATE: "STOP_CREATE",
  STOP_EDIT: "STOP_EDIT",
  STOP_DELETE: "STOP_DELETE",

  // Trip Management
  TRIP_VIEW: "TRIP_VIEW",
  TRIP_CREATE: "TRIP_CREATE",
  TRIP_EDIT: "TRIP_EDIT",
  TRIP_DELETE: "TRIP_DELETE",
  TRIP_DETAILS_VIEW: "TRIP_DETAILS_VIEW",
  TRIP_DETAILS_EDIT: "TRIP_DETAILS_EDIT",
  TRIP_CANCEL: "TRIP_CANCEL",
  TRIP_PASSENGERS_VIEW: "TRIP_PASSENGERS_VIEW",
  TRIP_STATUS_UPDATE: "TRIP_STATUS_UPDATE",

  // User Management
  USER_VIEW: "USER_VIEW",
  USER_EDIT: "USER_EDIT",
  USER_BLOCK: "USER_BLOCK",
  USER_DELETE: "USER_DELETE",
  USER_BOOKINGS_VIEW: "USER_BOOKINGS_VIEW",
  USER_PAYMENT_VIEW: "USER_PAYMENT_VIEW",

  // Booking Management
  BOOKING_VIEW: "BOOKING_VIEW",
  BOOKING_CREATE: "BOOKING_CREATE",
  BOOKING_EDIT: "BOOKING_EDIT",
  BOOKING_CANCEL: "BOOKING_CANCEL",
  BOOKING_PAYMENT_VIEW: "BOOKING_PAYMENT_VIEW",
  BOOKING_PAYMENT_VERIFY: "BOOKING_PAYMENT_VERIFY",

  // Analytics & Reports
  ANALYTICS_VIEW: "ANALYTICS_VIEW",
  ANALYTICS_VIEW_ALL: "ANALYTICS_VIEW_ALL",
  REVENUE_VIEW: "REVENUE_VIEW",
  REPORTS_GENERATE: "REPORTS_GENERATE",
  REPORTS_EXPORT: "REPORTS_EXPORT",

  // Live Tracking
  TRACKING_VIEW: "TRACKING_VIEW",
  TRACKING_MONITOR: "TRACKING_MONITOR",
  TRACKING_HISTORY: "TRACKING_HISTORY",

  // Support & Notifications
  SUPPORT_TICKET_VIEW: "SUPPORT_TICKET_VIEW",
  SUPPORT_TICKET_CREATE: "SUPPORT_TICKET_CREATE",
  SUPPORT_TICKET_EDIT: "SUPPORT_TICKET_EDIT",
  SUPPORT_TICKET_RESOLVE: "SUPPORT_TICKET_RESOLVE",
  NOTIFICATION_VIEW: "NOTIFICATION_VIEW",
  NOTIFICATION_SEND: "NOTIFICATION_SEND",

  // Admin & Role Management
  ADMIN_VIEW: "ADMIN_VIEW",
  ADMIN_CREATE: "ADMIN_CREATE",
  ADMIN_EDIT: "ADMIN_EDIT",
  ADMIN_DELETE: "ADMIN_DELETE",
  ADMIN_SUSPEND: "ADMIN_SUSPEND",
  ADMIN_PASSWORD_RESET: "ADMIN_PASSWORD_RESET",
  ROLE_VIEW: "ROLE_VIEW",
  ROLE_CREATE: "ROLE_CREATE",
  ROLE_EDIT: "ROLE_EDIT",
  ROLE_DELETE: "ROLE_DELETE",
  PERMISSION_VIEW: "PERMISSION_VIEW",
  PERMISSION_MANAGE: "PERMISSION_MANAGE",

  // System Settings
  SYSTEM_SETTINGS_VIEW: "SYSTEM_SETTINGS_VIEW",
  SYSTEM_SETTINGS_EDIT: "SYSTEM_SETTINGS_EDIT",
  SYSTEM_LOGS_VIEW: "SYSTEM_LOGS_VIEW",
  SYSTEM_BACKUP: "SYSTEM_BACKUP",

  // Stop Suggestions
  SUGGESTIONS_VIEW: "SUGGESTIONS_VIEW",
  SUGGESTIONS_REVIEW: "SUGGESTIONS_REVIEW",
  SUGGESTIONS_DELETE: "SUGGESTIONS_DELETE",

  // Coupons & Promotions
  COUPON_VIEW: "COUPON_VIEW",
  COUPON_CREATE: "COUPON_CREATE",
  COUPON_EDIT: "COUPON_EDIT",
  COUPON_DELETE: "COUPON_DELETE",

  // Financial Management
  FINANCIAL_VIEW: "FINANCIAL_VIEW",
  FINANCIAL_MANAGE: "FINANCIAL_MANAGE",
  SETTLEMENTS_MANAGE: "SETTLEMENTS_MANAGE",

  // Referral & Rewards
  REWARDS_VIEW: "REWARDS_VIEW",
  REWARDS_EDIT: "REWARDS_EDIT",
  REWARDS_DELETE: "REWARDS_DELETE",

  // Vehicle Rentals
  RENTAL_VIEW: "RENTAL_VIEW",
  RENTAL_EDIT: "RENTAL_EDIT",
  RENTAL_DELETE: "RENTAL_DELETE",
} as const;

export type PermissionSlug = typeof PERMISSIONS[keyof typeof PERMISSIONS];
